# Generated by Django 4.1.3 on 2022-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_gender', models.CharField(choices=[('ME', 'Male'), ('FE', 'Female')], max_length=2)),
                ('product_category', models.CharField(choices=[('JACKETS', 'Jackets'), ('TSHIRTS', 'T-Shirts'), ('HOODIES', 'Hoodies')], max_length=20)),
                ('product_sizes', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
