# Generated by Django 4.1.3 on 2022-12-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0002_ordereditems_shoppingcart_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditems',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
