# Generated by Django 4.1.3 on 2022-12-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0003_rename_price_ordereditems_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='total_price',
        ),
    ]
