# Generated by Django 4.1.3 on 2022-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
