# Generated by Django 4.1.3 on 2022-12-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0004_remove_ordereditems_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
    ]
