# Generated by Django 4.1.4 on 2022-12-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0005_shoppingcart_cart_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cart_name',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='final_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsketch.product')),
                ('shopping_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsketch.shoppingcart')),
            ],
        ),
    ]
