# Generated by Django 4.1.3 on 2022-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0005_remove_shoppingcart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
