# Generated by Django 4.1.4 on 2022-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0006_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
