# Generated by Django 4.1.4 on 2022-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0007_shoppingcart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='final_cost',
            field=models.IntegerField(null='true'),
        ),
    ]
