# Generated by Django 4.1.4 on 2022-12-08 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopsketch', '0008_alter_shoppingcart_final_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='name',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='owner',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to=settings.AUTH_USER_MODEL),
            preserve_default='true',
        ),
    ]
