# Generated by Django 4.1.4 on 2022-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsketch', '0009_remove_shoppingcart_name_shoppingcart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='final_cost',
        ),
    ]
