# Generated by Django 4.1.3 on 2022-11-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0010_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='data_dodania',
        ),
    ]
