# Generated by Django 4.1.3 on 2022-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.IntegerField(default=11),
        ),
    ]
