# Generated by Django 4.1.3 on 2022-11-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab5', '0004_person_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
    ]
