# Generated by Django 4.1.3 on 2022-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab5', '0006_person_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='can_view_other_persons',
            field=models.BooleanField(default=False),
        ),
    ]
