# Generated by Django 4.1.3 on 2022-12-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab5', '0004_alter_person_created_at_month'),
        ('lab5', '0007_person_can_view_other_persons'),
    ]

    operations = [
    ]
